version: '3'


services:

  db:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      postgres:

  app:
    build: .
    ports:
      - "8080:8080"
    image: teap
    depends_on:
      - db
    networks:
      postgres:
    env_file:
      - .env

networks:
  postgres: